### ISSUE TITLE
Unexpected behavior when filtering `find` queries of ZTF_exposures tables

### ISSUE THREAD

**Issue by zvanderbosch** [dmitryduev/penquins#26]
When performing a `find` query on any ZTF_exposures table in kowalski, gloria, or melman, errors are being returned whenever any filtering criteria are applied. As an example, if I want to query the ZTF_exposures_20210401 table on gloria for all exposures that have been acquired in the g-band in field 562, ccd 4, quad 3, I compose and execute the following query:

```python
from penquins import Kowalski

exp_query = {
    'query_type': 'find',
    'query' : {
        'catalog': 'ZTF_exposures_20210401',
        'filter': {
            'field': int(562),
            'ccd': int(4),
            'quad': int(3),
            'filter': int(1)
        },
        'projection': {
            '_id': 0
        }
    }
}

gloria = Kowalski(
    token=my_token,
    protocol='https',
    host='gloria.caltech.edu',
    port=443
)
response = gloria.query(query=exp_query)
```
The resulting error message is quite long, but basically looks like a timeout error:

```python
ReadTimeoutError: HTTPSConnectionPool(host='gloria.caltech.edu', port=443): Read timed out. (read timeout=5)
```

If I change the query to include a limit on the number of returned entries that is smaller than the total number of entries that match the filtering criteria, then the query will work, such as:

```python
exp_query = {
    'query_type': 'find',
    'query' : {
        'catalog': 'ZTF_exposures_20210401',
        'filter': {
            'field': int(562),
            'ccd': int(4),
            'quad': int(3),
            'filter': int(1)
        },
        'projection': {
            '_id': 0
        }
    },
    'kwargs': {
        'limit': 10
    }
}
```

For this particular field+ccd+quad+filter, I can increase the `limit` up to 243 without any errors, but at 244 I get the same timeout error as before. Presumably, 243 is the total number of entries that match the filtering criteria. If I knew the total number beforehand, I could work with this, but the `count_documents` query is also failing in the same way as the queries above. For example, the following query also results in a timeout error:

```python
doc_query = {
    'query_type': 'count_documents',
    'query' : {
        'catalog': 'ZTF_exposures_20210401',
        'filter': {
            'field': int(562),
            'ccd': int(4),
            'quad': int(3),
            'filter': int(1),
        },
    }
}
response = gloria.query(query=doc_query)
```

The expected behavior for all of these queries would be to simply return the maximum number of entries that match the filtering criteria when no `limit` is set, or when the `limit` value is greater than the number of matching entries. This is how queries on other tables behave, such as the following query into the ZTF_sources_20210401 table:

```python
source_query = {
    'query_type': 'find',
    'query' : {
        'catalog': 'ZTF_sources_20210401',
        'filter': {
            'field': int(562),
            'ccd': int(4),
            'quad': int(3),
            'filter': int(1)
        },
        'projection': {
            '_id': 0
        }
    }
}
response = gloria.query(query=source_query)
```

which successfully returns 27,400 entries.

I am running this code using penquins `2.2.0` and python `3.8.15`.

**Comment by mcoughlin** [comment]
@Theodlz @bfhealy

**Comment by mcoughlin** [comment]
@zvanderbosch I think requiring the users to paginate queries when a lot of data is returned from giant tables is not unreasonable.  @Theodlz @bfhealy Maybe we can provide some example code in the docs to help users who want to make queries where pagination is required?

**Comment by zvanderbosch** [comment]
@mcoughlin Yeah that's reasonable, but for pagination wouldn't you want to know beforehand how many table entries you expect to pass the filtering criteria? Since the `count_documents` query is failing in the same way when filters are applied, I don't see an obvious way to figure out how many queries would be needed to paginate the returned entries, or how to set the `limit` value on the final query to prevent a `ReadTimeoutError`.

Also just to clarify, I've tested this on multiple ZTF fields, and the timeout errors always occur right when the `limit` value exceeds the exact number of entries that pass the filters. So for a quadrant with 1000 exposures, the query would fail when `limit=1001`, and for a field with 10 exposures, the query would fail when `limit=11`.

**Comment by mcoughlin** [comment]
@Theodlz any ideas what would make that table special? Maybe "limit" doesn't make sense for this particular table somehow?

**Comment by bfhealy** [comment]
Maybe the quantity of data being queried per source is larger for the ZTF_exposures collection versus ZTF_sources? That could produce a timeout for one but not the other, even when querying the same number of sources. I've also found that `count_documents` times out, but it is possible to paginate a query without knowing the number of sources to expect.

I think [this code](https://github.com/ZwickyTransientFacility/scope/blob/main/tools/get_quad_ids.py) from scope might be a useful example of paginating queries until an unknown maximum is reached. The two functions to focus on are `get_ids_loop` and `get_field_ids`. `get_ids_loop` queries ZTF_sources with a fixed limit that is known not to time out, and it continues querying by calling `get_field_ids` and appending results using the `limit` and `skip` kwargs until the number of entries returned by a query is less than the fixed limit.

**Comment by zvanderbosch** [comment]
@bfhealy Yeah that works for the ZTF_sources tables, but with the behavior I'm experiencing with the ZTF_exposures tables, the final query in such a loop where the number of entries is less than the fixed limit would result in a ReadTimeoutError.

**Comment by zvanderbosch** [comment]
Update: @Theodlz figured out that there wasn't an index available for the columns I was trying to filter on in the exposures table, namely the field, ccd, quadrant, and filter IDs. He added an index for those and the queries above are now working without error, and without having to supply any value limit kwarg. @Theodlz can comment if I'm missing anything here, but I think this can be closed.

**Comment by Theodlz** [comment]
This can be closed yep! Let me know if any more indexing on this table or any other.

**Comment by Theodlz** [comment]
@mcoughlin I can't close stuff on penquins, could you do it? thanks
